version: 2
project_name: todoer

before:
  hooks:
    - go test ./...

builds:
  - id: todoer
    main: ./cmd/todoer
    binary: todoer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archives
    formats: 
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - todoer
    files:
      - LICENSE
      - README.md

kos:
  - id: docker_images
    build: todoer
    repositories: 
      - ghcr.io/inful/todoer
    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: "checksums.txt"

changelog:
  use: git