project_name: todoer

before:
  hooks:
    - go test ./...

builds:
  - id: todoer
    main: ./cmd/todoer
    binary: todoer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archives
    builds:
      - todoer
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  use: git